#!/usr/bin/env ruby

########################################################################
# Update the file CallbackUrl.java
# Jun-15-2014 
########################################################################
class UpdateCallbackUrl
  ME = File.basename($0)
  def initialize
  end

  def check_args
    if ARGV.length != 1
      puts <<EOF
  Usage: #{ME} <type>
  Valid type is: local, gae-test or gae-prod
EOF
      exit 1
    end
  end

  def generate_callbackurl(type)
    url = ''
    case type
    when 'local'
      url = 'http://oauthdemo2014.com:8888/GWTOAuthLoginDemo.html'
    when 'gae-test'
      url = 'https://gwtoauthlogindemo-test.appspot.com/GWTOAuthLoginDemo.html'
    when 'gae-prod'
      url = 'https://gwtoauthlogindemo-latest.appspot.com/GWTOAuthLoginDemo.html'
    end
    t = Time.new
    puts <<EOF
package com.example.GWTOAuthLoginDemo.client.OAuth;

/*
** WARNING: This file is auto generated by #{ME}. DO NOT MODIFY
** Generated on: #{t}
** Development Type: #{type} 
*/

public class OurCallbackUrl
{
    public OurCallbackUrl() { }
    public static final String APP_CALLBACK_URL = "#{url}";    
}
EOF
  end

  def doit
    check_args
    type = ''
    case ARGV[0]
    when "local"
      type = 'local'
    when "gae-test"
      type = 'gae-test'
    when "gae-prod"
      type = 'gae-prod'
    else
      puts "ERROR: unknown type: #{ARGV[0]}"
      exit 1
    end
    generate_callbackurl(type)
    exit 0
  end
end

if __FILE__ == $0
  UpdateCallbackUrl.new.doit
end
