package com.example.GWTOAuthLoginDemo.server.util;

/*
** WARNING: This file is auto generated by yaml2java.rb . DO NOT MODIFY
** Generated on : 2014-06-22 14:56:55 -0400
** Input file: /Users/muquit/gitdev/gwtoauthlogindemo/misc/local.yaml
*/
public class OAuthParams
{
    public OAuthParams() { }
    /* created as oauthlogindemo2012@g on Jun-22-2014 */
    public static final String FACEBOOK_APP_NAME = "OAuthLoginDemo";
    public static final String FACEBOOK_APP_ID = "534691036564570";
    public static final String FACEBOOK_APP_SECRET = "859e5c07f4d8835f25c051950c2cdf2f";

    /* created as oauthlogindemo2012 on Jun-17-2014 */
    public static final String GOOGLE_APP_NAME = "OAuthLoginDemo-Dev";
    public static final String GOOGLE_APP_ID = "1097316969626-aii65o4sum4hml7uovumultp7sl1dgs7.apps.googleusercontent.com";
    public static final String GOOGLE_APP_SECRET = "aAr2cnjk1BZyVoRE-Nr7odwQ";
    public static final String GOOGLE_SCOPE = "https://www.googleapis.com/auth/userinfo.profile";

    /* registered as oauthlogindemo2012 on Jun-22-2014 */
    public static final String TWITTER_APP_NAME = "OAuthLoginDemo";
    public static final String TWITTER_APP_ID = "ILl8GsVcr5tf51P5xAvu1Ox3H";
    public static final String TWITTER_APP_SECRET = "roxfgO8GQd5kfK7G7GR74tXBISJ3jzxQK1BhfiF328X30I2wL2";

    public static final String YAHOO_APP_NAME = "OAuthLoginDemo";
    public static final String YAHOO_APP_ID = "dj0yJmk9d2JHS0FHcDRNM1V2JmQ9WVdrOWVHcHRaa1ZpTm5VbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD04Yg--";
    public static final String YAHOO_APP_SECRET = "3f561b01d6bf4fdf5434478837296a22b744e075";

    /* registered as oauthlogindemo@gmail on Jun-22-2014 */
    public static final String INSTAGRAM_APP_NAME = "OAuthLoginDemo";
    public static final String INSTAGRAM_APP_ID = "b1e23080a9754c88805c421070a79e7b";
    public static final String INSTAGRAM_APP_SECRET = "adafc82a7ec34689ac734a8b76b15eed";

    /* registered as oauthlogindemo2012@ on Jun-19-2014 */
    public static final String LINKEDIN_APP_NAME = "OAuthLoginDemo";
    public static final String LINKEDIN_APP_ID = "77qdzsi1tb3k3o";
    public static final String LINKEDIN_APP_SECRET = "snewaDGzvslpUSt1";
    public static final String LINKEDIN_USER_TOKEN = "XYZ";
    public static final String LINKEDIN_USER_SECRET = "XYZ";

    public static final String GITHUB_APP_NAME = "OAuthLoginDemo";
    public static final String GITHUB_APP_ID = "ee3810bacf1c16b024de";
    public static final String GITHUB_APP_SECRET = "a0826c84b3c57c270605bf12bddc99e26b1abe12";

    /* registered as oauthdemo2012@yahoo, does not use redirect url */
    public static final String FLICKR_APP_NAME = "OAuthLoginDemo";
    public static final String FLICKR_APP_ID = "4cda3073a98234ff91e1edf0f94054a1";
    public static final String FLICKR_APP_SECRET = "825fa1fad4742353";

    public static final String IMGUR_APP_NAME = "OAuthLoginDemo";
    public static final String IMGUR_APP_ID = "5de89977fe51b0497fd485f656f2215c050c3be63";
    public static final String IMGUR_APP_SECRET = "105e221a68f6c7fd1a740b158e7c6ab3";

    /* updated as oauthdemo2012 for local Jun-16-2014 */
    public static final String VIMEO_APP_NAME = "OAuthLoginDemo";
    public static final String VIMEO_APP_ID = "1da15c8713a852006c1af1d34f4858e05e4b9ec1";
    public static final String VIMEO_APP_SECRET = "68226fb03d2fdde302053b2ac03294a23a68dddc";

    public static final String EVERNOTE_APP_NAME = "OAuthLoginDemo";
    public static final String EVERNOTE_APP_ID = "oauthdemo2012";
    public static final String EVERNOTE_APP_SECRET = "05aae97837ab74ee";

    /* registered as oauthlogindemo2012@live on Jun-22-2014 */
    public static final String WINDOWSLIVE_APP_NAME = "OAuthLoginDemo";
    public static final String WINDOWSLIVE_APP_ID = "0000000044120A78";
    public static final String WINDOWSLIVE_APP_SECRET = "3AawlwlYNcjA5fxIqWzLwVrfdbBvYq8g";

    /* registered as oauthdemo2012@gmail Jun-22-2014 */
    public static final String TUMBLRLIVE_APP_NAME = "OAuthLoginDemo";
    public static final String TUMBLRLIVE_APP_ID = "RS1iTRIL0lHKiL93Re4np90LMEEJWvTZqeCjxptNL585fVUfAA";
    public static final String TUMBLRLIVE_APP_SECRET = "iTRk8uMTVMae3tBF6bzbMCFHcfMyXE35JOVGEMBZjluA69mPfJ";

    public static final String FOURSQUARE_APP_NAME = "OAuthLoginDemo";
    public static final String FOURSQUARE_APP_ID = "301QER4O2VJ2P35F4IX2VKAYPPE0UBF4GVDCSC1HCS3TW5FQ";
    public static final String FOURSQUARE_APP_SECRET = "D5AALHCQ0NCMXQ5VOD2PEFPTCYWLKL0ZJG0K3X25Q1E0IN52";

}
