package com.example.GWTOAuthLoginDemo.server.util;

/*
** WARNING: This file is auto generated by yaml2java.rb . DO NOT MODIFY
** Generated on : 2014-06-26 17:57:09 -0400
** Input file: /Users/muquit/gitdev/gwtoauthlogindemo/misc/gae_test.yaml
*/
public class OAuthParams
{
    public OAuthParams() { }
    /* registered as oauthlogindemo@g on Jun-22-2014 */
    public static final String FACEBOOK_APP_NAME = "OAuthLoginDemo";
    public static final String FACEBOOK_APP_ID = "673575189381960";
    public static final String FACEBOOK_APP_SECRET = "154aceb7c3b0aab01fa6c76933dcd485";

    /* created as oauthlogindemo2012 on Jun-17-2014 */
    public static final String GOOGLE_APP_NAME = "OAuthLoginDemo Tes";
    public static final String GOOGLE_APP_ID = "1050909057443-7n6qu0g5hl9vfh4hevavkqbv000cjm2h.apps.googleusercontent.com";
    public static final String GOOGLE_APP_SECRET = "6T8264o26Djs9Tf1w0jtlne3";
    public static final String GOOGLE_SCOPE = "https://www.googleapis.com/auth/userinfo.profile";

    /* registered as oauthlogindemo2012 on Jun-22-2014 */
    public static final String TWITTER_APP_NAME = "OAuthLoginDemo";
    public static final String TWITTER_APP_ID = "yOPdUo0V2e3XmKyVz6o0hMlNo";
    public static final String TWITTER_APP_SECRET = "mPvb7SsxEAVqYtwvefJtj8Q6qnWJhDU4ERKEQVw6Wz6kgguqRN";

    /* registered as oauthdemo2012 on Jun-22-2014 */
    public static final String YAHOO_APP_NAME = "OAuthLoginDemo";
    public static final String YAHOO_APP_ID = "dj0yJmk9Wm5ON2J4NG9DRjlKJmQ9WVdrOWFVbFJSRTF2Tkc4bWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD03ZQ--";
    public static final String YAHOO_APP_SECRET = "81e15aff764a0c8a7f5eae921ba194597ef63717";

    /* registered as oauthlogindemo2012 on Jun-22-2014 */
    public static final String INSTAGRAM_APP_NAME = "OAuthLoginDemo";
    public static final String INSTAGRAM_APP_ID = "078573531d0e452a80fbe881fc5947a8";
    public static final String INSTAGRAM_APP_SECRET = "3fb0e46575f840ee81a9d4761450f463";

    public static final String LINKEDIN_APP_NAME = "OAuthLoginDemo";
    public static final String LINKEDIN_APP_ID = "cpmiob5h1fsu";
    public static final String LINKEDIN_APP_SECRET = "LgqI00Ckkf4xbagM";
    public static final String LINKEDIN_USER_TOKEN = "XYZ";
    public static final String LINKEDIN_USER_SECRET = "XYZ";

    /* updated as oauthdemo2012 Jun-15-2014 */
    public static final String GITHUB_APP_NAME = "OAuthLoginDemo";
    public static final String GITHUB_APP_ID = "d9b5ef35a01150fc5ca7";
    public static final String GITHUB_APP_SECRET = "babd91bc973bc72070c2550061b63ab37d88094e";

    /* registered as oauthdemo2012@yahoo, does not use redirect url */
    public static final String FLICKR_APP_NAME = "OAuthLoginDemo";
    public static final String FLICKR_APP_ID = "4cda3073a98234ff91e1edf0f94054a1";
    public static final String FLICKR_APP_SECRET = "825fa1fad4742353";

    public static final String IMGUR_APP_NAME = "OAuthLoginDemo";
    public static final String IMGUR_APP_ID = "5de89977fe51b0497fd485f656f2215c050c3be63";
    public static final String IMGUR_APP_SECRET = "105e221a68f6c7fd1a740b158e7c6ab3";

    /* updated as oauthdemo2012 Jun-16-2014 */
    public static final String VIMEO_APP_NAME = "OAuthLoginDemo";
    public static final String VIMEO_APP_ID = "203ddd0ee75113259b70397abea323bcd506c000";
    public static final String VIMEO_APP_SECRET = "03bccb6b6c79230b2a4ff863438688919e55dba5";

    public static final String EVERNOTE_APP_NAME = "OAuthLoginDemo";
    public static final String EVERNOTE_APP_ID = "oauthdemo2012";
    public static final String EVERNOTE_APP_SECRET = "05aae97837ab74ee";

    /* registered as oauthdemo2012 on Jun-22-2014 */
    public static final String WINDOWSLIVE_APP_NAME = "OAuthLoginDemo";
    public static final String WINDOWSLIVE_APP_ID = "0000000040123776";
    public static final String WINDOWSLIVE_APP_SECRET = "fcsKEkXcBpa8e6VD9IpbvljbYalh6MZW";

    /* registered as oauthdemo2012@gmail on Jun-22-2014 */
    public static final String TUMBLRLIVE_APP_NAME = "OAuthLoginDemo";
    public static final String TUMBLRLIVE_APP_ID = "Fb4s0LUqthPIhi1XgCDu0gTCwUWOCskuKMzyXpGMvOlWGn27oa";
    public static final String TUMBLRLIVE_APP_SECRET = "mynombuOvChMWDgRBbttzgLylcU2xBmvnRbB2G2P9SXQjOdSgn";

    public static final String FOURSQUARE_APP_NAME = "OAuthLoginDemo";
    public static final String FOURSQUARE_APP_ID = "301QER4O2VJ2P35F4IX2VKAYPPE0UBF4GVDCSC1HCS3TW5FQ";
    public static final String FOURSQUARE_APP_SECRET = "D5AALHCQ0NCMXQ5VOD2PEFPTCYWLKL0ZJG0K3X25Q1E0IN52";

}
