package com.example.GWTOAuthLoginDemo.client.util;

/*
** WARNING: This file is auto generated by gen_callback_url.rb. DO NOT MODIFY
** Generated on: 2014-06-22 14:56:54 -0400
** Development Type: local 
*/

public class CallbackUrl
{
    public CallbackUrl() { }
    public static final String APP_CALLBACK_URL = "http://oauthdemo2014.com:8888/GWTOAuthLoginDemo.html";    
}
