package com.example.GWTOAuthLoginDemo.client.util;

/*
** WARNING: This file is auto generated by gen_callback_url.rb. DO NOT MODIFY
** Generated on: 2014-06-26 17:57:08 -0400
** Development Type: gae-test 
*/

public class CallbackUrl
{
    public CallbackUrl() { }
    public static final String APP_CALLBACK_URL = "https://gwtoauthlogindemo-test.appspot.com/GWTOAuthLoginDemo.html";    
}
