package com.example.GWTOAuthLoginDemo.server.OAuth;

/*
** WARNING: This file is auto generated by yaml2java.rb . DO NOT MODIFY
** Generated on : 2014-07-06 14:13:34 -0400
** Input file: template.yaml
*/
public class OurOAuthParams
{
    public OurOAuthParams() { }
    /* Your comment */
    public static final String FACEBOOK_APP_NAME = "Your app_name";
    public static final String FACEBOOK_API_KEY = "Your api_key";
    public static final String FACEBOOK_API_SECRET = "Your api_secret";

    /* Your comment */
    public static final String FLICKR_APP_NAME = "Your app_name";
    public static final String FLICKR_API_KEY = "Your api_key";
    public static final String FLICKR_API_SECRET = "Your api_secret";

    /* Your comment */
    public static final String FOURSQUARE_APP_NAME = "Your app_name";
    public static final String FOURSQUARE_API_KEY = "Your api_key";
    public static final String FOURSQUARE_API_SECRET = "Your api_secret";

    /* Your comment */
    public static final String GITHUB_APP_NAME = "Your app_name";
    public static final String GITHUB_API_KEY = "Your api_key";
    public static final String GITHUB_API_SECRET = "Your api_secret";

    /* Your comment */
    public static final String GOOGLE_APP_NAME = "Your app_name";
    public static final String GOOGLE_API_KEY = "Your api_key";
    public static final String GOOGLE_API_SECRET = "Your api_secret";
    public static final String GOOGLE_SCOPE = "Your scope";

    /* Your comment */
    public static final String IMGUR_APP_NAME = "Your app_name";
    public static final String IMGUR_API_KEY = "Your api_key";
    public static final String IMGUR_API_SECRET = "Your api_secret";

    /* Your comment */
    public static final String INSTAGRAM_APP_NAME = "Your app_name";
    public static final String INSTAGRAM_API_KEY = "Your api_key";
    public static final String INSTAGRAM_API_SECRET = "Your api_secret";

    /* Your comment */
    public static final String LINKEDIN_APP_NAME = "Your app_name";
    public static final String LINKEDIN_API_KEY = "Your api_key";
    public static final String LINKEDIN_API_SECRET = "Your api_secret";
    public static final String LINKEDIN_USER_TOKEN = "Your user_token";
    public static final String LINKEDIN_USER_SECRET = "Your user_secret";

    /* Your comment */
    public static final String TUMBLRLIVE_APP_NAME = "Your app_name";
    public static final String TUMBLRLIVE_API_KEY = "Your api_key";
    public static final String TUMBLRLIVE_API_SECRET = "Your api_secret";

    /* Your comment */
    public static final String TWITTER_APP_NAME = "Your app_name";
    public static final String TWITTER_API_KEY = "Your api_key";
    public static final String TWITTER_API_SECRET = "Your api_secret";

    /* Your comment */
    public static final String VIMEO_APP_NAME = "Your app_name";
    public static final String VIMEO_API_KEY = "Your api_key";
    public static final String VIMEO_API_SECRET = "Your api_secret";

    /* Your comment */
    public static final String WINDOWSLIVE_APP_NAME = "Your app_name";
    public static final String WINDOWSLIVE_API_KEY = "Your api_key";
    public static final String WINDOWSLIVE_API_SECRET = "Your api_secret";

    /* Your comment */
    public static final String YAHOO_APP_NAME = "Your app_name";
    public static final String YAHOO_API_KEY = "Your api_key";
    public static final String YAHOO_API_SECRET = "Your api_secret";

}
