package com.example.GWTOAuthLoginDemo.server.OAuth;

/*
** WARNING: This file is auto generated by yaml2java.rb . DO NOT MODIFY
** Generated on : 2014-07-06 00:51:23 -0400
** Input file: gae_production.yaml
*/
public class OurOAuthParams
{
    public OurOAuthParams() { }
    /* registered as oauthlogindemo@g on Jun-29-2014 */
    public static final String AWEBER_APP_NAME = "GWTOAuthLoginDemo";
    public static final String AWEBER_API_KEY = "AkHxsly52po4cVp4zd325toY";
    public static final String AWEBER_API_SECRET = "6Bc7yjjfaMTrtHoeDtuOn6NvRdkBLeuoTTqHik7D";

    /* registered as oauthlogindemo@g on Jun-22-2014 */
    public static final String FACEBOOK_APP_NAME = "GWTOAuthLoginDemo";
    public static final String FACEBOOK_API_KEY = "419645444843694";
    public static final String FACEBOOK_API_SECRET = "a19d9fa5580c3c41764931ac049b5ad2";

    /* registered as oauthlogindemo2012 on Jun-17-2014 */
    public static final String GOOGLE_APP_NAME = "GWTOAuthLoginDemo-Dev";
    public static final String GOOGLE_API_KEY = "254652073349-bbrqnfagnsdddm9ou4r84rh1bub5orlj.apps.googleusercontent.com";
    public static final String GOOGLE_API_SECRET = "VfMokvOQ3zm66lNTzE2RkjZD";
    public static final String GOOGLE_SCOPE = "https://www.googleapis.com/auth/userinfo.profile";

    /* registered as oauthlogindemo2012 on Jun-22-2014 */
    public static final String TWITTER_APP_NAME = "GWTOAuthLoginDemo";
    public static final String TWITTER_API_KEY = "Oxz2sUBtYWgx2AVHBz2GJGoqY";
    public static final String TWITTER_API_SECRET = "hY2PQDn4Xw99xYaKtHNb0j6tbBAGVCQMmY0dHk0jf64qa6EvDO";

    /* registered as oauthdemo2012 Jun-16-2014 */
    public static final String YAHOO_APP_NAME = "GWTOAuthLoginDemo";
    public static final String YAHOO_API_KEY = "dj0yJmk9Wkg5V0Q0aFhobjhzJmQ9WVdrOWRHZFpUVE14Tm04bWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1iYg--";
    public static final String YAHOO_API_SECRET = "2ab574d78157aa4dcd5e0308a7436c5a446cf885";

    /* registered as oauthlogindemo2012 on Jun-22-2014 */
    public static final String INSTAGRAM_APP_NAME = "GWTOAuthLoginDemo";
    public static final String INSTAGRAM_API_KEY = "6dc706e565ef4017a597a0bf8db125f7";
    public static final String INSTAGRAM_API_SECRET = "59930e58f4c948b9b3c879ca2b8cc80f";

    /* updated as oauthdemo2012@gmail Jun-27-2014 */
    public static final String LINKEDIN_APP_NAME = "GWTOAuthLoginDemo";
    public static final String LINKEDIN_API_KEY = "77ii1mj6xcv7en";
    public static final String LINKEDIN_API_SECRET = "lu5HHqFHFp6QQrBI";
    public static final String LINKEDIN_USER_TOKEN = "XYZ";
    public static final String LINKEDIN_USER_SECRET = "XYZ";

    public static final String GITHUB_APP_NAME = "GWTOAuthLoginDemo";
    public static final String GITHUB_API_KEY = "3339659e33bec9abbef4";
    public static final String GITHUB_API_SECRET = "aff2c04c02e77cb10f296873f846b367b8136ff0";

    /* registered as oauthdemo2012@yahoo, does not use redirect url */
    public static final String FLICKR_APP_NAME = "GWTOAuthLoginDemo";
    public static final String FLICKR_API_KEY = "4cda3073a98234ff91e1edf0f94054a1";
    public static final String FLICKR_API_SECRET = "825fa1fad4742353";

    public static final String IMGUR_APP_NAME = "GWTOAuthLoginDemo";
    public static final String IMGUR_API_KEY = "5de89977fe51b0497fd485f656f2215c050c3be63";
    public static final String IMGUR_API_SECRET = "105e221a68f6c7fd1a740b158e7c6ab3";

    /* updated as oauthdemo2012 Jun-16-2014 */
    public static final String VIMEO_APP_NAME = "GWTOAuthLoginDemo";
    public static final String VIMEO_API_KEY = "1ca90668d87737d3b39d3f61b3eff3785e45c5a0";
    public static final String VIMEO_API_SECRET = "0d4ea8938319892c8e5e76cec840ceea1f6a6962";

    public static final String EVERNOTE_APP_NAME = "GWTOAuthLoginDemo";
    public static final String EVERNOTE_API_KEY = "oauthdemo2012";
    public static final String EVERNOTE_API_SECRET = "05aae97837ab74ee";

    /* registered as oauthdemo2012 on Jun-22-2014 */
    public static final String WINDOWSLIVE_APP_NAME = "GWTOAuthLoginDemo";
    public static final String WINDOWSLIVE_API_KEY = "0000000040123777";
    public static final String WINDOWSLIVE_API_SECRET = "q3swaBVbGaUVdaqEuPPQGRX00FkZ3mVZ";

    /* registered as oauthdemo2012@gmail on Jun-22-2014 */
    public static final String TUMBLRLIVE_APP_NAME = "GWTOAuthLoginDemo";
    public static final String TUMBLRLIVE_API_KEY = "AUv036uUfM7uXlyh2aMowLgIZYdtr6bRzO7Wr9CCSsD95E84ek";
    public static final String TUMBLRLIVE_API_SECRET = "z2dMPLwTA6kSivy4dNro9FzZsOUIk3vKQErkZp1N1AxdSlVBNp";

    /* registered as oauthdemo2012@gmail on Jun-29-2014 */
    public static final String FOURSQUARE_APP_NAME = "GWTOAuthLoginDemo";
    public static final String FOURSQUARE_API_KEY = "RCYZYRNVMI34TNKE5054JMFNLFKTKNOSLPT34GN4IZM215PF";
    public static final String FOURSQUARE_API_SECRET = "NJQGUFMW2M5JGCDPOONTOBXKXSGL4WY4QXZXNFUGPGRCNX2M";

}
