package com.example.GWTOAuthLoginDemo.server.OAuth;

/*
** WARNING: This file is auto generated by yaml2java.rb . DO NOT MODIFY
** Generated on : 2014-07-04 16:45:55 -0400
** Input file: local.yaml
*/
public class OurOAuthParams
{
    public OurOAuthParams() { }
    /* created as oauthdemo2012@g on Jun-22-2014 */
    public static final String FACEBOOK_APP_NAME = "GWTOAuthLoginDemo";
    public static final String FACEBOOK_API_KEY = "534691036564570";
    public static final String FACEBOOK_API_SECRET = "859e5c07f4d8835f25c051950c2cdf2f";

    /* registered as oauthdemo2012@yahoo, does not use redirect url */
    public static final String FLICKR_APP_NAME = "GWTOAuthLoginDemo";
    public static final String FLICKR_API_KEY = "4cda3073a98234ff91e1edf0f94054a1";
    public static final String FLICKR_API_SECRET = "825fa1fad4742353";

    /* registered as oauthdemo2012@gmail Jun-22-2014 */
    public static final String FOURSQUARE_APP_NAME = "GWTOAuthLoginDemo";
    public static final String FOURSQUARE_API_KEY = "1MZ4BX3TITYP5DKFNEHZ0RJO4NK4FTGPZUEKVRCC1QLQFJWT";
    public static final String FOURSQUARE_API_SECRET = "WDDPWLKVAEOXIC5OKWSYS1A4YNR2JREUQK25NHCTTTY2DEJP";

    /* updated as oauthdemo2012 Jun-22-2014 */
    public static final String GITHUB_APP_NAME = "GWTOAuthLoginDemo";
    public static final String GITHUB_API_KEY = "ee3810bacf1c16b024de";
    public static final String GITHUB_API_SECRET = "a0826c84b3c57c270605bf12bddc99e26b1abe12";

    /* created as oauthdemo2012 on Jun-17-2014 */
    public static final String GOOGLE_APP_NAME = "GWTOAuthLoginDemo-Dev";
    public static final String GOOGLE_API_KEY = "1097316969626-aii65o4sum4hml7uovumultp7sl1dgs7.apps.googleusercontent.com";
    public static final String GOOGLE_API_SECRET = "aAr2cnjk1BZyVoRE-Nr7odwQ";
    public static final String GOOGLE_SCOPE = "https://www.googleapis.com/auth/userinfo.profile";

    /* registered as oauthdemo2012@gmail on Jun-29-2014 */
    public static final String IMGUR_APP_NAME = "GWTOAuthLoginDemo";
    public static final String IMGUR_API_KEY = "37386d0a5ce6ef6";
    public static final String IMGUR_API_SECRET = "bf9bc0f280e120a759561b28fcb785f380284d4d";

    /* registered as oauthlogindemo2012@gmail on Jun-22-2014 */
    public static final String INSTAGRAM_APP_NAME = "GWTOAuthLoginDemo";
    public static final String INSTAGRAM_API_KEY = "b1e23080a9754c88805c421070a79e7b";
    public static final String INSTAGRAM_API_SECRET = "adafc82a7ec34689ac734a8b76b15eed";

    /* registered as oauthlogindemo2012@ on Jun-19-2014 */
    public static final String LINKEDIN_APP_NAME = "GWTOAuthLoginDemo";
    public static final String LINKEDIN_API_KEY = "77qdzsi1tb3k3o";
    public static final String LINKEDIN_API_SECRET = "snewaDGzvslpUSt1";
    public static final String LINKEDIN_USER_TOKEN = "XYZ";
    public static final String LINKEDIN_USER_SECRET = "XYZ";

    /* registered as oauthdemo2012@gmail Jun-22-2014 */
    public static final String TUMBLRLIVE_APP_NAME = "GWTOAuthLoginDemo";
    public static final String TUMBLRLIVE_API_KEY = "RS1iTRIL0lHKiL93Re4np90LMEEJWvTZqeCjxptNL585fVUfAA";
    public static final String TUMBLRLIVE_API_SECRET = "iTRk8uMTVMae3tBF6bzbMCFHcfMyXE35JOVGEMBZjluA69mPfJ";

    /* registered as oauthlogindemo2012 on Jun-22-2014 */
    public static final String TWITTER_APP_NAME = "GWTOAuthLoginDemo";
    public static final String TWITTER_API_KEY = "ILl8GsVcr5tf51P5xAvu1Ox3H";
    public static final String TWITTER_API_SECRET = "roxfgO8GQd5kfK7G7GR74tXBISJ3jzxQK1BhfiF328X30I2wL2";

    /* updated as oauthdemo2012 for local Jun-16-2014 */
    public static final String VIMEO_APP_NAME = "GWTOAuthLoginDemo";
    public static final String VIMEO_API_KEY = "1da15c8713a852006c1af1d34f4858e05e4b9ec1";
    public static final String VIMEO_API_SECRET = "68226fb03d2fdde302053b2ac03294a23a68dddc";

    /* registered as oauthlogindemo2012@live on Jun-22-2014 */
    public static final String WINDOWSLIVE_APP_NAME = "GWTOAuthLoginDemo";
    public static final String WINDOWSLIVE_API_KEY = "0000000044120A78";
    public static final String WINDOWSLIVE_API_SECRET = "3AawlwlYNcjA5fxIqWzLwVrfdbBvYq8g";

    /* registered as oauthdemo2012 on Jun-22-2014 */
    public static final String YAHOO_APP_NAME = "GWTOAuthLoginDemo";
    public static final String YAHOO_API_KEY = "dj0yJmk9Mmt6RjdwMEhrdWJVJmQ9WVdrOVRuZ3pXa2xVTTJNbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD0xOQ--";
    public static final String YAHOO_API_SECRET = "a78cf79cf0f5b5c9a2be057e79e23dad9f3e54c8";

}
