#!/usr/bin/env ruby

########################################################################
# Create the MyImages interface from image file names
# Muhammad.Muquit@usc-bt.com 
########################################################################
class MakeMyImages
  ME = $0

  def initialize
    @dir = ''
  end
  def check_args
    if ARGV.length != 1
      puts <<EOD
  #{ME} <dir>
EOD
      exit 1
    end
    @dir = ARGV[0]
  end

  def doit
    check_args
    t = Time.new
    puts <<EOD
/**
 * Auto Generated by mk_images.rb on #{t}
 */
public interface MyImages extends ClientBundle
{
EOD
    images = Dir.entries(@dir)
    images.each do |f|
      next if f == "." or f == ".."
      puts "    @Source(\"#{@dir}/#{f}\")"
      if f =~ /(.*)\..*$/
      puts "    public DataResource #{$1}IconImageData();\n\n"
      end
    end
  puts <<EOD
}
EOD
  end
end

if __FILE__ == $0
  MakeMyImages.new.doit
end


