package com.example.GWTOAuthLoginDemo.client.resources.images;

import com.google.gwt.resources.client.ClientBundle;
import com.google.gwt.resources.client.DataResource;

/**
 * Auto Generated by mk_images.rb on Fri Nov 30 22:39:12 -0500 2012
 */
public interface MyImages extends ClientBundle
{
    @Source("32px/facebook.png")
    public DataResource facebookIconImageData();

    @Source("32px/flickr.png")
    public DataResource flickrIconImageData();

    @Source("32px/github.png")
    public DataResource githubIconImageData();

    @Source("32px/google.png")
    public DataResource googleIconImageData();

    @Source("32px/linkedin.png")
    public DataResource linkedinIconImageData();

    @Source("32px/twitter.png")
    public DataResource twitterIconImageData();

    @Source("32px/vimeo.png")
    public DataResource vimeoIconImageData();

    @Source("32px/wordpress.png")
    public DataResource wordpressIconImageData();

    @Source("32px/yahoo.png")
    public DataResource yahooIconImageData();
    
    @Source("32px/instagram.png")
    public DataResource instagramIconImageData();
    
    @Source("32px/imgur.png")
    public DataResource imgurIconImageData();
    
    @Source("32px/live32.png")
    public DataResource liveIconImageData();
    
    @Source("32px/tumblr.png")
    public DataResource tumblrIconImageData();
    
    @Source("32px/foursquare.png")
    public DataResource foursquareIconImageData();
    
    @Source("32px/close.png")
    public DataResource closeIconImageData();
    
    @Source("32px/busy.gif")
    public DataResource busyIconImageData();
    
}
