#!/usr/bin/env ruby

require 'yaml'
require_relative 'oauth_params.rb'

########################################################################
# Update the file CallbackUrl.java
# Jun-15-2014 
########################################################################
class UpdateCallbackUrl
  ME = File.basename($0)
  def initialize
  end

  def check_args
    if ARGV.length != 1
      puts <<EOF
  Usage: #{ME} <type>
  Valid type is: local, gae-test, gae-prod, push
EOF
      exit 1
    end
  end

  def generate_callbackurl(type)
    url = ''
    dir = File.expand_path(File.dirname(__FILE__))
    base_dir = File.dirname(dir)

    case type
    when 'local'
      yaml_file = base_dir + "/private/local.yaml"
    when 'gae-test'
      yaml_file = base_dir + "/private/gae_test.yaml"
    when 'gae-prod'
      yaml_file = base_dir + "/private/gae_production.yaml"
    end
    if !File.exists?(yaml_file)
    puts <<EOF
ERROR: File '#{yaml_file}' does not exist"
Please copy the file template.yaml and update
EOF
      exit
    end
    yaml = YAML::load_file(yaml_file)
    url = yaml.redirect_url
    t = Time.new
    c = ''
    source = File.basename(yaml_file)
    puts <<EOF
package com.example.GWTOAuthLoginDemo.client.OAuth;

/*
** WARNING: This file is auto generated by #{ME}. 
** Source: private/#{source}
** DO NOT MODIFY
** Generated on: #{t}
** Development Type: #{type} 
*/

public class OurCallbackUrl
{
    public OurCallbackUrl() { }
    public static final String APP_CALLBACK_URL = "#{url}";    
}
EOF
  end

  def doit
    check_args
    type = ''
    case ARGV[0]
    when "local"
      type = 'local'
    when "gae-test"
      type = 'gae-test'
    when "gae-prod"
      type = 'gae-prod'
    else
      puts "ERROR: unknown type: #{ARGV[0]}"
      exit 1
    end
    generate_callbackurl(type)
    exit 0
  end
end

if __FILE__ == $0
  UpdateCallbackUrl.new.doit
end
