#!/usr/bin/env ruby

require 'yaml'
require 'pp'
require_relative 'oauth_params.rb'

# create a java file file from yaml file with oauth params
# muquit@muquit.com Jun-15-2014 
class MakeYamlFromServerUtilsJava
  ME = File.basename($0)
  def initialize
  end

  def generate_java(yaml_file)
    t = Time.new
    puts <<EOF
package com.example.GWTOAuthLoginDemo.server.OAuth;

/*
** WARNING: This file is auto generated by #{ME} . DO NOT MODIFY
** Generated on : #{t}
** Input file: #{ARGV[0]}
*/
public class OurOAuthParams
{
    public OurOAuthParams() { }
EOF

    o = YAML::load_file(yaml_file)
    providers = o.providers
    providers.each do |provider,params|
      if params.has_key?('comment')
        comment = params['comment']
        puts "    /* #{comment} */"
      end
      params.each do |k,v|
        next if k == 'comment'
        s = provider.upcase + "_" + k.upcase
        puts "    public static final String #{s} = \"#{v}\";"
      end
      puts "\n"
    end
    puts <<EOF
}
EOF
    rescue => e
      puts "ERROR: #{e}"
  end

  def doit
    if ARGV.length != 1
      puts <<EOF
  Usage: #{ME} <file.yaml>
EOF
      exit 1
    end
    generate_java(ARGV[0])
  end
end

if __FILE__ == $0
  MakeYamlFromServerUtilsJava.new.doit
end
