package com.example.GWTOAuthLoginDemo.client.OAuth;

/*
** WARNING: This file is auto generated by gen_callback_url.rb. 
** Source: private/template.yaml
** DO NOT MODIFY
** Generated on: 2014-07-05 19:24:12 -0400
*/

public class OurCallbackUrl
{
    public OurCallbackUrl() { }
    public static final String APP_CALLBACK_URL = "http://your_domain:8888/GWTOAuthLoginDemo.html";    
}
