package com.example.GWTOAuthLoginDemo.client.OAuth;

/*
** WARNING: This file is auto generated by gen_callback_url.rb. 
** Source: private/gae_production.yaml
** DO NOT MODIFY
** Generated on: 2014-07-06 00:51:22 -0400
*/

public class OurCallbackUrl
{
    public OurCallbackUrl() { }
    public static final String APP_CALLBACK_URL = "https://gwtoauthlogindemo-latest.appspot.com/GWTOAuthLoginDemo.html";    
}
