package com.example.GWTOAuthLoginDemo.client.OAuth;

/*
** WARNING: This file is auto generated by gen_callback_url.rb. DO NOT MODIFY
** Generated on: 2014-07-01 10:17:53 -0400
** Development Type: local 
*/

public class OurCallbackUrl
{
    public OurCallbackUrl() { }
    public static final String APP_CALLBACK_URL = "http://oauthdemo2014.com:8888/GWTOAuthLoginDemo.html";    
}
